spring:
  datasource:
    url: jdbc:mysql://localhost:3307/commondb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    sql:
      init:
        mode: always
  management:
    endpoints:
      web:
        exposure:
          include: "*"
