spring:
  datasource:
    url: jdbc:mysql://localhost:3307/microservice
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
      init:
        mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
